/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceSlugRouteImport } from './routes/$workspaceSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSlugIndexRouteImport } from './routes/$workspaceSlug.index'
import { Route as SettingsStorageRouteImport } from './routes/settings.storage'
import { Route as BoardBoardIdRouteImport } from './routes/board.$boardId'
import { Route as WorkspaceSlugBoardIdRouteImport } from './routes/$workspaceSlug.$boardId'

const WorkspaceSlugRoute = WorkspaceSlugRouteImport.update({
  id: '/$workspaceSlug',
  path: '/$workspaceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugIndexRoute = WorkspaceSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)
const SettingsStorageRoute = SettingsStorageRouteImport.update({
  id: '/settings/storage',
  path: '/settings/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardBoardIdRoute = BoardBoardIdRouteImport.update({
  id: '/board/$boardId',
  path: '/board/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSlugBoardIdRoute = WorkspaceSlugBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => WorkspaceSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/$workspaceSlug/$boardId': typeof WorkspaceSlugBoardIdRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workspaceSlug/$boardId': typeof WorkspaceSlugBoardIdRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/$workspaceSlug': typeof WorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workspaceSlug': typeof WorkspaceSlugRouteWithChildren
  '/$workspaceSlug/$boardId': typeof WorkspaceSlugBoardIdRoute
  '/board/$boardId': typeof BoardBoardIdRoute
  '/settings/storage': typeof SettingsStorageRoute
  '/$workspaceSlug/': typeof WorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$workspaceSlug'
    | '/$workspaceSlug/$boardId'
    | '/board/$boardId'
    | '/settings/storage'
    | '/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$workspaceSlug/$boardId'
    | '/board/$boardId'
    | '/settings/storage'
    | '/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/$workspaceSlug'
    | '/$workspaceSlug/$boardId'
    | '/board/$boardId'
    | '/settings/storage'
    | '/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkspaceSlugRoute: typeof WorkspaceSlugRouteWithChildren
  BoardBoardIdRoute: typeof BoardBoardIdRoute
  SettingsStorageRoute: typeof SettingsStorageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$workspaceSlug': {
      id: '/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/$workspaceSlug'
      preLoaderRoute: typeof WorkspaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/': {
      id: '/$workspaceSlug/'
      path: '/'
      fullPath: '/$workspaceSlug/'
      preLoaderRoute: typeof WorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
    '/settings/storage': {
      id: '/settings/storage'
      path: '/settings/storage'
      fullPath: '/settings/storage'
      preLoaderRoute: typeof SettingsStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$boardId': {
      id: '/board/$boardId'
      path: '/board/$boardId'
      fullPath: '/board/$boardId'
      preLoaderRoute: typeof BoardBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$workspaceSlug/$boardId': {
      id: '/$workspaceSlug/$boardId'
      path: '/$boardId'
      fullPath: '/$workspaceSlug/$boardId'
      preLoaderRoute: typeof WorkspaceSlugBoardIdRouteImport
      parentRoute: typeof WorkspaceSlugRoute
    }
  }
}

interface WorkspaceSlugRouteChildren {
  WorkspaceSlugBoardIdRoute: typeof WorkspaceSlugBoardIdRoute
  WorkspaceSlugIndexRoute: typeof WorkspaceSlugIndexRoute
}

const WorkspaceSlugRouteChildren: WorkspaceSlugRouteChildren = {
  WorkspaceSlugBoardIdRoute: WorkspaceSlugBoardIdRoute,
  WorkspaceSlugIndexRoute: WorkspaceSlugIndexRoute,
}

const WorkspaceSlugRouteWithChildren = WorkspaceSlugRoute._addFileChildren(
  WorkspaceSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkspaceSlugRoute: WorkspaceSlugRouteWithChildren,
  BoardBoardIdRoute: BoardBoardIdRoute,
  SettingsStorageRoute: SettingsStorageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
